[package]
name = "transaction-engine"
version = "0.1.0"
authors = ["Thomas Schreiber"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
csv = "1.1.6"
rust_decimal = "1.10.3"
serde = { version = "1.0.125", features = ["derive"] }